### ISSUE TITLE
Random startup problems during initialisation

### ISSUE THREAD

**Issue by JohnnyKaramello** [RobPo/Paperino#2]
display sometimes does not update, unplugging and restarting usually helps

**Comment by RobPo** [comment]
I think this has to do with the busy pin during the ic driver initialisation; which can be undefined during the hardware reset ... the function waitForBusyIncative() then waits eternally. Lets try the new code lines. If it's OK then it will flow in the upcoming release and we can close the issue...

**Comment by RobPo** [comment]
Btw, display not updating is not good!

**Comment by RobPo** [comment]
Should be fixed with recent update (using pull request next time).
