### ISSUE TITLE
Use SPIsettings() to allow SPI slaves with different SPI settings

### ISSUE THREAD

**Issue by RobPo** [RobPo/Paperino#4]
SPIsettings()  is available since firmware 0.6.1 - it allows usage of SPI slaves with different bus settings. Furthermore we could save three lines of code ;-) - Please implement

**Comment by JohnnyKaramello** [comment]
maybe keep both version in the examples and put the corresponding firmware version as a comment
e.g.

SPIsetting(...) //for firmware version 0.61
//SPI1.begin() //for firmware version 0.5.x

**Comment by RobPo** [comment]
Ok I'd like to keep the code clean and as short as possible (to lower the barriers): Since Particle makes it easy to upgrade to the latest firmware version (which should be done anyway), I will add a comment in comment-section so everybody should be aware of the minimum required firmware release.

**Comment by RobPo** [comment]
Implemented in [last release](https://github.com/RobPo/Paperino/releases/tag/v1.0.20)
